### ISSUE TITLE
Prevent Poison from proccing Curse of Midas

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/prophets-of-the-labyrinth-Archive#260]

**Comment by bobaguardian** [comment]
@ntseng can I get more information on this: what is the bug and desired behavior?

**Comment by ntseng** [comment]
Poison is a debuff that cause the bearer to take damage after they take an action.

Curse of Midas is a modifier that causes gold to be added to the loot pool when the bearer takes damage.

Currently, Curse of Midas doesn't filter for damage done via Poison, which is definitionally correct, but somewhat unintuitive. It would be better if Curse of Midas only triggered on direct weapon damage.

**Comment by bobaguardian** [comment]
Okok just to reclarify right now if the bearer has both poison and curse of midas and they take dmg for poison, it's NOT increasing the loot from curse of midas but we want it to?

**Comment by ntseng** [comment]
The reverse: loot is increasing, which is weird.

**Comment by bobaguardian** [comment]
Icic gotcha. Thanks for clarifying!
