### ISSUE TITLE
Crash on interacting with archived thread

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/prophets-of-the-labyrinth-Archive#281]
![image](https://user-images.githubusercontent.com/6503151/160181506-2f8f653d-5712-4fae-b9a5-0676ff1697ab.png)

**Comment by ntseng** [comment]
https://discord.js.org/#/docs/discord.js/stable/class/ThreadChannel?scrollTo=setArchived

**Comment by ntseng** [comment]
Probably also a problem for Locked threads

**Comment by ntseng** [comment]
@doubledh I can't figure out repro steps on this one. Error code 50093 is "Tried to perform an operation on an archived thread, such as editing a message or adding a user to the thread". However, I can't figure out which operation is causing the error, slash commands unarchive the thread and message components are disabled in archived threads, so I'm not sure where the entry point is that allows the thread to stay archived.

Additionally, the error occurred in an adventure where the route vote race condition also occurred, but I can't think of a way the race condition causes this bad state.

**Comment by doubledh** [comment]
Adding notes that we exhaustively looked at all points where edit/update could happen on archived threads
- components are disabled on archived threads
- slash-commands unarchive threads 
- join button on the outside isn't really in the thread to begin with
- all uses of edits-without-replies came from some component

**Comment by ntseng** [comment]
Dismissing due to lack of reproducibility.
