### ISSUE TITLE
Weapon: Vigilance Charm

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/prophets-of-the-labyrinth-Archive#373]
### Discussed in https://github.com/Imaginary-Horizons-Productions/prophets-of-the-labyrinth/discussions/259

<div type='discussions-op-text'>

<sup>Originally posted by **ntseng** March 16, 2022</sup>
Applies a modifier to user that prevents block from being removed between rounds.

Upgrades:
- Allow targeting allies
- Guarding</div>

**Comment by doubledh** [comment]
earth trinket
