### ISSUE TITLE
Tell players how many weapon slots they have somewhere

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/prophets-of-the-labyrinth-Archive#379]

**Comment by bobaguardian** [comment]
I was thinking we can put it in the "Inspect Self" message right before the weapons are listed.  Something like Weapons (2/5)?

**Comment by ntseng** [comment]
That seems like a good place to put it. I'd also try a placeholder weapon slot field and see which one is easier to read.
