### ISSUE TITLE
Combine "Gold on Fire" and "Free Gold?" events

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/prophets-of-the-labyrinth-Archive#381]

**Comment by bobaguardian** [comment]
I forget what we discussed for this but its free gold but surprise fire damage right?

**Comment by ntseng** [comment]
Surprise narratively, but mechanically it should be random whether it does damage or not.

The goal of the event would be to give the players 2 choices:
1. Is it worth X gold to risk Y gold?
2. Who has hp to spare in case it goes bad?

In that sense, marking the damage and/or chance on the button would be good for gameplay.

**Comment by bobaguardian** [comment]
Oh okok I just implemented it as surprise dmg rn, but we want to do the dmg on chance?

**Comment by bobaguardian** [comment]
![potl-freegoldonfire](https://user-images.githubusercontent.com/12629902/166391337-a4aaf49c-878f-4f72-a17f-9d5a08e1e4bd.JPG)

**Comment by ntseng** [comment]
My bad on forgetting to put the ideas here. Give the damage on chance a try, it'll probably give some insight on how things work. Let me know if you have any questions!
