### ISSUE TITLE
Test for race condition in weapon target select

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/prophets-of-the-labyrinth-Archive#406]

**Comment by doubledh** [comment]
It is the case that the moves are cleared out after the then, but there is ALSO a checkNextRound after the then, so even with multiple callbacks going at the same time from different players, each callback will still go by the checkNextRound which will acknowledge a previous callback's endround (and the cleanup of the move queue)

**Comment by doubledh** [comment]
Therefore, targeting moves / consumables / nontargeting moves do not currently have a race-condition (that matters)

**Comment by doubledh** [comment]
also, there is an initial round check (but there is a tiiiiiiny racecondition possible where everything is still working rather correctly (a person may manage to actually change target at the same time the last move is enqueued)
