### ISSUE TITLE
 merge logic from Move.calculateTotalSpeed() and Combatant.calculateTotalSpeed()

### ISSUE THREAD

**Issue by doubledh** [Imaginary-Horizons-Productions/prophets-of-the-labyrinth-Archive#476]

**Comment by doubledh** [comment]
also rename setter to settotalspeed

**Comment by ntseng** [comment]
From the linked PR:
> Instead of refactoring the move speed handlers to a pure setter, this PR documents the existing architecture. A pure setter was deemed to cause too much code duplication, as the prior mentioned responsibilities would have to be re-implemented in 5 different places currently.
> 
> The function Move.calculateMoveSpeed() has been renamed to Move.onSetMoveSpeed() to expand its responsibility to include housing the logic for enemy speed mechanics and the consumption of Quicken/Slow stacks.
